"""create generacion table

Revision ID: 4091038fe226
Revises: 4f9665879c50
Create Date: 2025-06-08 16:12:40.694387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4091038fe226'
down_revision: Union[str, None] = '4f9665879c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generacion',
    sa.Column('index', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pk_recurso', sa.Text(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('hora', sa.Integer(), nullable=True),
    sa.Column('generacion', sa.Float(), nullable=True),
    sa.Column('fecha_actuali', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generacion')
    # ### end Alembic commands ###
