"""create demanda real table, updte name columns and delete user table test

Revision ID: 4f9665879c50
Revises: 865c6b58ef9a
Create Date: 2025-06-08 16:09:44.317945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9665879c50'
down_revision: Union[str, None] = '865c6b58ef9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demanda_real',
    sa.Column('index', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_demanda_re', sa.Text(), nullable=True),
    sa.Column('pk_agente', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('hora', sa.Integer(), nullable=True),
    sa.Column('demanda_rea', sa.Float(), nullable=True),
    sa.Column('fecha_actuali', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    op.drop_table('usuarios')
    op.add_column('agentes', sa.Column('pk_agente', sa.Text(), nullable=True))
    op.add_column('agentes', sa.Column('actividad', sa.String(), nullable=True))
    op.add_column('agentes', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('agentes', sa.Column('fecha_actual', sa.Date(), nullable=True))
    op.drop_column('agentes', 'Estado')
    op.drop_column('agentes', 'pkAgente')
    op.drop_column('agentes', 'Actividad')
    op.drop_column('agentes', 'fecha_actuali')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentes', sa.Column('fecha_actuali', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('agentes', sa.Column('Actividad', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agentes', sa.Column('pkAgente', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agentes', sa.Column('Estado', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('agentes', 'fecha_actual')
    op.drop_column('agentes', 'estado')
    op.drop_column('agentes', 'actividad')
    op.drop_column('agentes', 'pk_agente')
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('correo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey'))
    )
    op.drop_table('demanda_real')
    # ### end Alembic commands ###
