"""create agentes table

Revision ID: 865c6b58ef9a
Revises: f28bb4590eed
Create Date: 2025-06-07 16:51:14.411989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '865c6b58ef9a'
down_revision: Union[str, None] = 'f28bb4590eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentes',
    sa.Column('index', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pkAgente', sa.Text(), nullable=True),
    sa.Column('Actividad', sa.String(), nullable=True),
    sa.Column('Estado', sa.String(), nullable=True),
    sa.Column('fecha_actuali', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    op.drop_table('"TablasXM_dev"."DemandaReal"')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('"TablasXM_dev"."DemandaReal"',
    sa.Column('IdDemandaReal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pkAgente', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('hora', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('demanda_real', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.drop_table('agentes')
    # ### end Alembic commands ###
