"""create temperatura solatable and change column name date for fecha

Revision ID: 90d8e06156c9
Revises: f83595f6cf64
Create Date: 2025-06-08 16:18:31.559894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90d8e06156c9'
down_revision: Union[str, None] = 'f83595f6cf64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperatura_solar',
    sa.Column('index', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pk_recurso', sa.Text(), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('fecha_actuali', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    op.add_column('demanda_real', sa.Column('fecha', sa.Date(), nullable=True))
    op.drop_column('demanda_real', 'date')
    op.add_column('generacion', sa.Column('fecha', sa.TIMESTAMP(), nullable=True))
    op.drop_column('generacion', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generacion', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('generacion', 'fecha')
    op.add_column('demanda_real', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('demanda_real', 'fecha')
    op.drop_table('temperatura_solar')
    # ### end Alembic commands ###
