"""create recursos table

Revision ID: f83595f6cf64
Revises: 4091038fe226
Create Date: 2025-06-08 16:15:09.305480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83595f6cf64'
down_revision: Union[str, None] = '4091038fe226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recursos',
    sa.Column('index', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pk_recurso', sa.Text(), nullable=True),
    sa.Column('pk_agente', sa.Text(), nullable=True),
    sa.Column('nombre_recurso', sa.Text(), nullable=True),
    sa.Column('tipo_recurso', sa.Text(), nullable=True),
    sa.Column('fecha_actuali', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recursos')
    # ### end Alembic commands ###
